alias g='git'
alias gst='git status'
alias gup='git pull --rebase'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias gpf!='git push --force'
alias gc='git commit -v'
alias gco='git checkout'
alias gcb='git checkout -b'
alias ga='git add'
alias gaa='git add .'
alias grh='git reset HEAD'
alias grhh='git reset HEAD --hard'
alias gclean='git reset --hard; and git clean -dfx'
alias dotfiles='/usr/bin/git --git-dir=$HOME/.cfg --work-tree=$HOME'
